declare const classNames: {
  readonly "game-dialog-wrapper": "game-dialog-wrapper";
  readonly "game-dialog": "game-dialog";
  readonly "message-group": "message-group";
  readonly messages: "messages";
  readonly author: "author";
  readonly content: "content";
  readonly "dialog-action": "dialog-action";
  readonly "messages-wrapper": "messages-wrapper";
  readonly "interrogation-wrapper": "interrogation-wrapper";
  readonly button: "button";
  readonly allow: "allow";
  readonly deny: "deny";
  readonly "is-pressed": "is-pressed";
  readonly "entrance-controls": "entrance-controls";
  readonly responses: "responses";
  readonly "is-scrollable": "is-scrollable";
  readonly scroller: "scroller";
};
export = classNames;
